// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Formats = require("./Formats.bs.js");
var JsonRpc = require("./JsonRpc.bs.js");

function getBalance(address) {
  var params = /* array */[Formats.encode(/* Address */Block.__(0, [address]))];
  return JsonRpc.jsonRpcRequest("eth_getBalance", params).then((function (result) {
                return Promise.resolve(Formats.Decode[/* quantity */0](result));
              }));
}

exports.getBalance = getBalance;
/* JsonRpc Not a pure module */
