// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var quantity = Caml_format.caml_int_of_string;

var Decode = /* module */[/* quantity */quantity];

function encode(value) {
  switch (value.tag | 0) {
    case 1 : 
        return Curry._1(Printf.sprintf(/* Format */[
                        /* String_literal */Block.__(11, [
                            "0x",
                            /* Int */Block.__(4, [
                                /* Int_x */6,
                                /* No_padding */0,
                                /* No_precision */0,
                                /* End_of_format */0
                              ])
                          ]),
                        "0x%x"
                      ]), value[0]);
    case 0 : 
    case 2 : 
        return value[0];
    
  }
}

exports.Decode = Decode;
exports.encode = encode;
/* No side effect */
