// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var Repromise = require("@aantron/repromise/src/js/repromise.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

((require('isomorphic-fetch')));

function fetchJson(url, payload) {
  return Repromise.Rejectable[/* catch */7]((function (param) {
                return Repromise.Rejectable[/* resolved */2](/* Error */Block.__(1, ["Error"]));
              }), Repromise.Rejectable[/* map */5]((function (json) {
                    return /* Ok */Block.__(0, [json]);
                  }), Repromise.Rejectable[/* andThen */4]((function (r) {
                        return Repromise.Rejectable[/* fromJsPromise */10](r.json());
                      }), Repromise.Rejectable[/* fromJsPromise */10](fetch(url, Fetch.RequestInit[/* make */0](/* Post */2, {
                                    "Content-Type": "application/json"
                                  }, Caml_option.some(JSON.stringify(payload)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0))))));
}

exports.fetchJson = fetchJson;
/*  Not a pure module */
